-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 01:55:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinica` ;

-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica` DEFAULT CHARACTER SET utf8 ;
USE `clinica` ;

-- -----------------------------------------------------
-- Table `clinica`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`pacientes` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(20) NOT NULL,
  `cedula` VARCHAR(13) NOT NULL,
  `direccion` VARCHAR(60) NULL,
  `telefono` VARCHAR(10) NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`especialidades` (
  `id_especialidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_especialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`medicos` (
  `id_medico` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(20) NOT NULL,
  `cedula` VARCHAR(13) NOT NULL,
  `telefono` VARCHAR(10) NULL,
  `email` VARCHAR(80) NULL,
  `especialidades_id_especialidad` INT NOT NULL,
  PRIMARY KEY (`id_medico`),
  CONSTRAINT `fk_medicos_especialidades1`
    FOREIGN KEY (`especialidades_id_especialidad`)
    REFERENCES `clinica`.`especialidades` (`id_especialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_medicos_especialidades1_idx` ON `clinica`.`medicos` (`especialidades_id_especialidad` ASC);


-- -----------------------------------------------------
-- Table `clinica`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`consultas` (
  `id_consulta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `pacientes_id_paciente` INT NOT NULL,
  `medicos_id_medico` INT NOT NULL,
  PRIMARY KEY (`id_consulta`),
  CONSTRAINT `fk_consultas_pacientes`
    FOREIGN KEY (`pacientes_id_paciente`)
    REFERENCES `clinica`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_medicos1`
    FOREIGN KEY (`medicos_id_medico`)
    REFERENCES `clinica`.`medicos` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_consultas_pacientes_idx` ON `clinica`.`consultas` (`pacientes_id_paciente` ASC);

CREATE INDEX `fk_consultas_medicos1_idx` ON `clinica`.`consultas` (`medicos_id_medico` ASC);


-- -----------------------------------------------------
-- Table `clinica`.`detalle_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`detalle_consulta` (
  `id_detalle_consulta` INT NOT NULL AUTO_INCREMENT,
  `diagnostico` VARCHAR(150) NULL,
  `tratamiento` VARCHAR(45) NULL,
  `consultas_id_consulta` INT NOT NULL,
  `indicaciones` VARCHAR(150) NULL,
  PRIMARY KEY (`id_detalle_consulta`),
  CONSTRAINT `fk_detalle_consulta_consultas1`
    FOREIGN KEY (`consultas_id_consulta`)
    REFERENCES `clinica`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalle_consulta_consultas1_idx` ON `clinica`.`detalle_consulta` (`consultas_id_consulta` ASC);


-- -----------------------------------------------------
-- Table `clinica`.`examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`examenes` (
  `id_examen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id_examen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`consulta_examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`consulta_examen` (
  `id_consulta_examen` INT NOT NULL AUTO_INCREMENT,
  `consultas_id_consulta` INT NOT NULL,
  `examenes_id_examen` INT NOT NULL,
  PRIMARY KEY (`id_consulta_examen`),
  CONSTRAINT `fk_consulta_examen_consultas1`
    FOREIGN KEY (`consultas_id_consulta`)
    REFERENCES `clinica`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_examen_examenes1`
    FOREIGN KEY (`examenes_id_examen`)
    REFERENCES `clinica`.`examenes` (`id_examen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_consulta_examen_consultas1_idx` ON `clinica`.`consulta_examen` (`consultas_id_consulta` ASC);

CREATE INDEX `fk_consulta_examen_examenes1_idx` ON `clinica`.`consulta_examen` (`examenes_id_examen` ASC);


-- -----------------------------------------------------
-- Table `clinica`.`recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`recetas` (
  `id_receta` INT NOT NULL AUTO_INCREMENT,
  `medicamento` VARCHAR(50) NOT NULL,
  `cantidad` INT NOT NULL,
  `posologia` VARCHAR(80) NOT NULL,
  `tipo_uso` VARCHAR(40) NOT NULL,
  `observaciones` VARCHAR(120) NULL,
  `consultas_id_consulta` INT NOT NULL,
  PRIMARY KEY (`id_receta`),
  CONSTRAINT `fk_recetas_consultas1`
    FOREIGN KEY (`consultas_id_consulta`)
    REFERENCES `clinica`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_recetas_consultas1_idx` ON `clinica`.`recetas` (`consultas_id_consulta` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
